# -*- coding: utf-8 -*-
"""Iris_SVM_Deploy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O6M-dNesBH_MuZqPZz7k2pvA6_dknmL0
"""

from sklearn import svm
from sklearn import datasets
import pickle

iris = datasets.load_iris()
X, y = iris.data, iris.target

clf = svm.SVC(C=1.0,probability=True, random_state=1)
clf.fit(X, y)

print('Training Accuracy: ', clf.score(X, y))

print('Prediction results: ', clf.predict_proba([[5.2,  3.5,  2.4,  1.2]]))

pickle.dump(clf , open('model.pkl','wb'))

model = pickle.load(open('model.pkl','rb'))
print(model.predict([[5.2,  3.5,  2.4,  1.2]]))